version: "3"

services:
  data_transport_layer:
    environment:
      - DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
      - DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
      - DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=http://geth_l2:8545
      - DATA_TRANSPORT_LAYER__L2_CHAIN_ID=
      - DATA_TRANSPORT_LAYER__DB_PATH=/db
      - DATA_TRANSPORT_LAYER__SERVER_PORT=7878
      - DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
      - DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=http://l1_chain:9545
      - DATA_TRANSPORT_LAYER__CONFIRMATIONS=0
      - DATA_TRANSPORT_LAYER__POLLING_INTERVAL=500
      - DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=2000
      - DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
      - DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=0.0.0.0
      - DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=
      - L1_NODE_WEB3_URL=http://l1_chain:9545
      - DEPLOYER_HTTP=http://deployer:8080

  geth_l2:
    environment:
      - ETH1_SYNC_SERVICE_ENABLE=true
      - ETH1_CTC_DEPLOYMENT_HEIGHT=8
      - ETH1_HTTP=http://l1_chain:9545
      - ETH1_CONFIRMATION_DEPTH=0
      - ROLLUP_CLIENT_HTTP=http://data_transport_layer:7878
      - ROLLUP_POLL_INTERVAL_FLAG=3s
      - USING_OVM=true
      - CHAIN_ID=420
      - NETWORK_ID=420
      - DEV=true
      - DATADIR=/root/.ethereum
      - RPC_ENABLE=true
      - RPC_ADDR=geth_l2
      - RPC_CORS_DOMAIN=*
      - RPC_VHOSTS=*
      - RPC_PORT=8545
      - WS=true
      - WS_ADDR=0.0.0.0
      - IPC_DISABLE=true
      - TARGET_GAS_LIMIT=9000000
      - RPC_API=eth,net,rollup,web3
      - WS_API=eth,net,rollup,web3
      - WS_ORIGINS=*
      - GASPRICE=0
      - NO_USB=true
      - GCMODE=archive
      - NO_DISCOVER=true
      - DEPLOYER_HTTP=http://deployer:8080

  batch_submitter:
    environment:
      - DEBUG=info*,error*,warn*,debug*
      - MAX_TX_SIZE=90000
      - MIN_TX_SIZE=0
      - MAX_BATCH_SIZE=50
      - POLL_INTERVAL=15000
      - NUM_CONFIRMATIONS=0
      - RESUBMISSION_TIMEOUT=1000000
      - FINALITY_CONFIRMATIONS=0
      - RUN_TX_BATCH_SUBMITTER=true
      - RUN_STATE_BATCH_SUBMITTER=true
      - MAX_BATCH_SUBMISSION_TIME=0
      - SAFE_MINIMUM_ETHER_BALANCE=0
      - CLEAR_PENDING_TXS=false
      - L1_NODE_WEB3_URL=http://l1_chain:9545
      - L2_NODE_WEB3_URL=http://geth_l2:8545
      - DEPLOYER_HTTP=http://deployer:8080
      - SEQUENCER_PRIVATE_KEY=0xd2ab07f7c10ac88d5f86f1b4c1035d5195e81f27dbe62ad65e59cbf88205629b
      - ADDRESS_MANAGER_ADDRESS=

  l1_chain:
    environment:
      - ETH1_HTTP_PORT=9545
      - MNEMONIC=abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about

  deployer:
    environment:
      - HARDHAT=true
      - FRAUD_PROOF_WINDOW_SECONDS=0
      - L1_NODE_WEB3_URL=http://l1_chain:9545
      - DEPLOYER_PRIVATE_KEY=0x754fde3f5e60ef2c7649061e06957c29017fe21032a8017132c0078e37f6193a
      - SEQUENCER_PRIVATE_KEY=0xd2ab07f7c10ac88d5f86f1b4c1035d5195e81f27dbe62ad65e59cbf88205629b

  integration_tests:
    environment:
      - foo=bar
      - L1_NODE_WEB3_URL=http://l1_chain:9545
      - L2_NODE_WEB3_URL=http://geth_l2:8545
      - MNEMONIC=abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about
      - DEPLOYER_HTTP=http://deployer:8080
      - CHAIN_ID=420
      - TARGET_GAS_LIMIT=9000000
      - DEPLOYER_URL=http://deployer:8080
      - DEPLOYER_PRIVATE_KEY=0x754fde3f5e60ef2c7649061e06957c29017fe21032a8017132c0078e37f6193a
      - SEQUENCER_PRIVATE_KEY=0xd2ab07f7c10ac88d5f86f1b4c1035d5195e81f27dbe62ad65e59cbf88205629b
      - ETH1_ADDRESS_RESOLVER_ADDRESS=
